CREATE DATABASE IF NOT EXISTS taskmanager CHARACTER SET utf8mb4;
USE taskmanager;
CREATE TABLE IF NOT EXISTS tasks (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 description TEXT NULL,
 is_done TINYINT(1) NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
